Lang: 'ja' # Language
AfkAutoTime: 300 # Second

# MySQL
UseMySQL: false
MySQLServer: '' # MySQL Server (MySQL5.6+)
MySQLUsername: '' # Username
MySQLPassword: '' # Password
MySQLDatabase: '' # Database
MySQLOption: '?allowPublicKeyRetrieval=true&useSSL=false' # ConnectOption (If you are not sure, do not change it.)